//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcunmedyaAkademiPortfolyo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAboutID
    {
        public int AboutID { get; set; }
        public string AboutBirthday { get; set; }
        public string AboutCity { get; set; }
        public string AboutEmail { get; set; }
        public string AboutEğitim { get; set; }
    }
}
