//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcunmedyaAkademiPortfolyo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblStatistic
    {
        public int StatisticsId { get; set; }
        public string StatsName { get; set; }
        public Nullable<int> StatsNumber { get; set; }
        public string StatsEmoji { get; set; }
    }
}
